controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    fairino3_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
fairino3_controller:
  ros__parameters:
    joints: [j1, j2, j3, j4, j5, j6]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
gripper_controller:
  ros__parameters:
    joints: [left_finger_joint, right_finger_joint]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    state_publish_rate: 30.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
